name = "captchapi"
main = "build/worker/shim.mjs"
compatibility_date = "2025-05-24"

assets = { directory = "./src/public", binding = "public" }

[observability.logs]
enabled = true

[[unsafe.bindings]]
name = "captchapi-rate-limiter"
type = "ratelimit"
namespace_id = "1"
simple = { limit = 5, period = 10 }

[limits]
cpu_ms = 1000

[build]
command = "cargo install -q worker-build && worker-build"